### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by maxischuh** [molML/s4-for-de-novo-drug-design#10]
Thanks for providing such a cool tool!
One question up front: would it be possible to share the pre-trained models from the paper?

Coming to my actual question, unfortunately I am struggling to get the tool to work on two separate instances.
On both machines I get the following error:
```bash
 File "generate_analogues.py", line 1, in <module>                                                                                                                      
    from s4dd import S4forDenovoDesign                                                                                                                                   
  File "/home/schuh/miniconda3/envs/s4_for_dd/lib/python3.8/site-packages/s4dd/__init__.py", line 1, in <module>                                                         
    from .s4_for_denovo_design import S4forDenovoDesign                                                                                                                  
  File "/home/schuh/miniconda3/envs/s4_for_dd/lib/python3.8/site-packages/s4dd/s4_for_denovo_design.py", line 14, in <module>                                            
    from .module_library.sequence_model import SequenceModel                                                                                                             
ModuleNotFoundError: No module named 's4dd.module_library' 
```

I hope there is a fix for this. Thanks!

Cheers,
Maxi

**Comment by shiningsunnyday** [comment]
Hi Maxi, I resolved this same issue by:
1. adding __init__.py in module_library so module_library is recognized as a package
2. replace the line in setup.py `packages=find_packages(),`
3. uninstall and reinstall `python -m pip install .`

also I think the pre-trained models are on the Zenodo, the link is in the README

**Comment by rizaozcelik** [comment]
Dear @maxischuh ,

Sorry for my delayed response. I was on vacation.

The `ModuleNotFound` error is a particularly annoying one and it may require a different fix per system. Next to what @shiningsunnyday suggested already, you can try adding `s4dd` to your `$PYTHONPATH` ([an example here](https://zenodo.org/records/11085650)). Despite being a non-ideal solution, this can work.

For pre-trained models (and more), you can see our [Zenodo repository](https://zenodo.org/records/11085650).

Let me know if you have further questions, or feel free to close the issue! 🙂

**Comment by maxischuh** [comment]
Thank you for your responses, @rizaozcelik and @shiningsunnyday.
I will test your suggestions! I also found the model.pt files :) 

Cheers,
Maxi
