### ISSUE TITLE
Bug? libmamba error: cannot install both pin-1-1 and pin-1-1

### ISSUE THREAD

**Issue by gmseabra** [molML/s4-for-de-novo-drug-design#2]
Hi guys,

Thanks a lot for making your research available.

I'm trying to install it locally, following the installation instructions in your readme file. However, in the next-to-last step, I get this weird error:

```
$ conda install --file requirements.txt -c conda-forge
Channels:
 - conda-forge
 - bioconda
 - defaults
 - https://repo.anaconda.com/pkgs/free
 - nvidia
 - pytorch
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: \ warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE                                                                                  failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - cannot install both pin-1-1 and pin-1-1

Could not solve for environment specs
The following packages are incompatible
└─ pin-1 is installable with the potential options
   ├─ pin-1 1, which can be installed;
   └─ pin-1 1 conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.8.* (labeled as 'pin-1')
```

Have you seen this before? Do you know how I could solve that?

Thanks!

**Comment by rizaozcelik** [comment]
Hi,

Thanks for your interest in our work!

We haven't experienced this issue before and I cannot reproduce it locally. So, I can only make an "educated guess" based suggestion.

I see that you're using `mamba` as the dependency solver. Switching to the default `conda` solver might help, despite being slower. To do that, you can use the command `conda install --file requirements.txt -c conda-forge --solver classic`

If this doesn't solve the issue, could you share the list of installed packages in the environment? To do so, you can run `conda activate s4_for_dd; conda list`.

Let me know how this goes. I wouldn't want Conda standing in your way 🙂  

Cheers.
