### ISSUE TITLE
Did you compare your results with that created by REINVENT

### ISSUE THREAD

**Issue by xuzhang5788** [molML/s4-for-de-novo-drug-design#5]
Thank you so much for your work. People prefer to use RL to enhance the final results for de-novo drug design to get better molecules that can have better activities. Did you compare your results with those created by such as REINVENT?

In addition, you use SMILES to represent molecules. Did you try to use SELFIES or SAFE?

**Comment by rizaozcelik** [comment]
Hey, thanks for your interest and nice words! 

S4 is an alternative to LSTMs and GPTs. Thus we compared S4 to those architectures using a well-established *de novo* design pipeline.

S4 can easily be integrated into reinforcement learning workflows (*e.g.,* REINVENT) as a prior, and/or trained on different molecular representations (*e.g.,* SELFIES and SAFE). All those ideas are waiting to be explored.

Cheers!

**Comment by xuzhang5788** [comment]
Thank you for your fast reply. Looking forward to your new explorations.
