### ISSUE TITLE
How to train custom training data? thank you！

### ISSUE THREAD

**Issue by CCCCCCCABC** [molML/s4-for-de-novo-drug-design#6]
Thank you for your work!

I would like to ask how to modify if we want to train on our own custom dataset (e.g. pre-training dataset or fine-tuning dataset)? I read the code, the key is the number of vocabulary? Can you give me some hints? 

Thanks!

**Comment by rizaozcelik** [comment]
Hi!

Thanks for your interest in our work! We have example scripts for [pertaining](https://github.com/molML/s4-for-de-novo-drug-design/blob/main/examples/pretraining.py) and [fine-tuning](https://github.com/molML/s4-for-de-novo-drug-design/blob/main/examples/finetuning.py). They might help you.

When it comes to `vocab_size`, `S4forDenovoDesign` supports providing a vocab size as parameter during initialization. For instance:

```python
s4 = S4forDenovoDesign(vocab_size=your_vocab_size)
```

Please let me know if this does not help. I can also better help if you share your code and the error messages you get, in case you get any.

Have fun!

**Comment by CCCCCCCABC** [comment]
> Hi!
> 
> Thanks for your interest in our work! We have example scripts for [pertaining](https://github.com/molML/s4-for-de-novo-drug-design/blob/main/examples/pretraining.py) and [fine-tuning](https://github.com/molML/s4-for-de-novo-drug-design/blob/main/examples/finetuning.py). They might help you.
> 
> When it comes to `vocab_size`, `S4forDenovoDesign` supports providing a vocab size as parameter during initialization. For instance:
> 
> ```python
> s4 = S4forDenovoDesign(vocab_size=your_vocab_size)
> ```
> 
> Please let me know if this does not help. I can also better help if you share your code and the error messages you get, in case you get any.
> 
> Have fun!

Thank you for your answer. 
I noticed the word segmentation operation on SMILES string in smiles_utils.py. Did you use this to get the vocabulary of the dataset and the corresponding quantity? 

thank you！

**Comment by rizaozcelik** [comment]
Yes, the vocabulary is extracted during the training of the model. See the following code block under `S4forDenovoDesign.train` (lines 291-309):

```python
train_dataloader = create_dataloader(
            training_molecules_path,
            batch_size=self.batch_size,
            sequence_length=self.sequence_length + 1,
            num_workers=1,
            shuffle=True,
            token2label=self.token2label,
        )
self.token2label = train_dataloader.dataset.token2label
self.label2token = {v: k for k, v in self.token2label.items()}

val_dataloader = create_dataloader(
    val_molecules_path,
    batch_size=self.batch_size,
    sequence_length=self.sequence_length + 1,
    num_workers=1,
    shuffle=True,
    token2label=self.token2label,
)
```
Here, `token2label` is the dictionary that contains the vocabulary entries. I guess you might be facing some issues in case the size of `token2label` is not matching with the `vocab_size` you provided to initialize the model. To solve the issue, as a preprocessing step, you can create the `token2label` dictionary in a different script and inspect its content and size (the code above can help you). Afterward, you can change the model creation parameters.

**Comment by CCCCCCCABC** [comment]
> Yes, the vocabulary is extracted during the training of the model. See the following code block under `S4forDenovoDesign.train` (lines 291-309):
> 
> ```python
> train_dataloader = create_dataloader(
>             training_molecules_path,
>             batch_size=self.batch_size,
>             sequence_length=self.sequence_length + 1,
>             num_workers=1,
>             shuffle=True,
>             token2label=self.token2label,
>         )
> self.token2label = train_dataloader.dataset.token2label
> self.label2token = {v: k for k, v in self.token2label.items()}
> 
> val_dataloader = create_dataloader(
>     val_molecules_path,
>     batch_size=self.batch_size,
>     sequence_length=self.sequence_length + 1,
>     num_workers=1,
>     shuffle=True,
>     token2label=self.token2label,
> )
> ```
> 
> Here, `token2label` is the dictionary that contains the vocabulary entries. I guess you might be facing some issues in case the size of `token2label` is not matching with the `vocab_size` you provided to initialize the model. To solve the issue, as a preprocessing step, you can create the `token2label` dictionary in a different script and inspect its content and size (the code above can help you). Afterward, you can change the model creation parameters.

Thank you ！
